- client/regions.go
- client/regions_test.go
> fix: update region URLs and add the mgl region

- .github/workflows/release.yml
> fix: change git config from local to global in release workflow

- .github/workflows/release.yml
> chore: add release creation step to workflow

- .github/workflows/release.yml
> chore: set GPG_TTY environment variable for GPG import

- .github/workflows/release.yml
> chore: update GPG signing key configuration in release workflow

- .github/workflows/unit-tests.yml
- sonar-project.properties
> chore: change sonar

- README.md
> docs: add supported products section and update retry config parameters

- LICENSE
- README.md
Change MGC Go SDK to Apache 2.0 licence
> feat: change licence from GPLv3 to Apache 2.0

- .github/pull_request_template.md
- .github/workflows/go-checks.yml
- README.md
> chore: update pull request template and improve go-checks workflow; enhance README with Block Storage details

- README.md
- audit/client.go
- audit/client_test.go
- audit/events.go
- audit/events_test.go
- audit/types.go
- audit/types_test.go
- cmd/examples/audit/main.go
- internal/utils/types.go
- internal/utils/types_test.go
> feat: add audit service with event and event type management

- cmd/examples/containerregistry/main.go
- containerregistry/client.go
- containerregistry/client_test.go
- containerregistry/credentials.go
- containerregistry/credentials_test.go
- containerregistry/images.go
- containerregistry/images_test.go
- containerregistry/registries.go
- containerregistry/registries_test.go
- containerregistry/repositories.go
- containerregistry/repositories_test.go
- internal/http/client.go
- internal/http/client_test.go
> feat: add container-registry

- .github/workflows/go-checks.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yml
> chore: improve workflow security

- internal/http/client_test.go
> chore: fix some warns

- README.md
- cmd/examples/compute/main.go
- cmd/examples/network/main.go
- network/client.go
- network/client_test.go
- network/ports.go
- network/ports_test.go
- network/public_ips.go
- network/public_ips_test.go
- network/rules.go
- network/rules_test.go
- network/security_groups.go
- network/security_groups_test.go
- network/subnetpools.go
- network/subnetpools_test.go
- network/subnets.go
- network/subnets_test.go
- network/vpcs.go
- network/vpcs_test.go
> feat: add network services support with VPCs, subnets, security groups, and rules

- README.md
- client/client.go
Adding documentation for region-specific endpoints and updating the default base URL in the client configuration.
> docs: update README to include region information and default region to BR-NE1

- client/errors.go
- client/errors_test.go
- internal/http/client.go
- internal/http/client_test.go
> feat: add RetryError type for handling max retry attempts

- blockstorage/volumes.go
- blockstorage/volumes_test.go
- cmd/examples/blockstorage/main.go
> fix: expands on get and list, and improve type struct

- cmd/examples/kubernetes_small/main.go
- kubernetes/cluster.go
- kubernetes/flavor.go
- kubernetes/nodepool.go
> feat: change nodepool

- cmd/examples/compute/main.go
- compute/instances.go
- compute/instances_test.go
> feat: update compute instances to return network instances in the new 1.1 api version

- cmd/examples/compute/main.go
- compute/instances.go
> feat: enhance instance creation with user data and labels

- compute/instances.go
> feat: add error handling structure to instance data model

- .github/workflows/go-checks.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yml
- go.mod
- go.sum
> chore: update go to 1.24

- blockstorage/snapshots.go
- cmd/examples/kubernetes/main.go
- cmd/examples/kubernetes_small/main.go
- kubernetes/cluster.go
- kubernetes/cluster_test.go
> fix: pointers

- cmd/examples/network/main.go
- network/ports.go
- network/ports_test.go
- network/public_ips.go
- network/public_ips_test.go
- network/rules.go
- network/rules_test.go
- network/security_groups.go
- network/security_groups_test.go
- network/subnetpools.go
- network/subnetpools_test.go
- network/subnets.go
- network/subnets_test.go
- network/vpcs.go
- network/vpcs_test.go
Following the pattern for all optional values be a pointer in go.
> feat: update network models to use pointer types for optional fields

- kubernetes/nodepool.go
> fix: k8s nodepool InstanceTemplate name adjust

- .github/workflows/unit-tests.yml
- update unit tests workflow to trigger only on pull requests
> chore: update unit tests workflow to trigger only on pull requests

- cmd/examples/kubernetes_small/main.go
- kubernetes/nodepool.go
- kubernetes/nodepool_test.go
> feat: add node list from nodepool

- cmd/examples/kubernetes/main.go
- cmd/examples/kubernetes_small/main.go
- kubernetes/flavor.go
- kubernetes/flavor_test.go
> fix: change k8s flavor list return type FlavorsAvailable

- kubernetes/cluster.go
> fix: wrong mapping json field

- cmd/examples/network/main.go
- network/subnets.go
- network/vpcs.go
- network/vpcs_test.go
- Now its possible to create ports and subnets with az information
> fix: add zone option to CreatePort and CreateSubnet methods

- availabilityzones/az.go
- availabilityzones/az_test.go
- cmd/examples/availabilityzones/main.go
> feat: improve az list return type

- cmd/examples/network/main.go
- network/vpcs.go
- network/vpcs_test.go
- Adjust network public ip create function to field description be a pointer
> fix: adjust network public ip to use pointer in description field

- cmd/examples/kubernetes/main.go
- cmd/examples/kubernetes_small/main.go
- kubernetes/cluster.go
- kubernetes/cluster_test.go
- kubernetes/nodepool.go
- Adjusts in the cluster and noodepools contracts
- Fixed pointers and missing fields
> fix: adjusting k8s nodepool and clusters contracts to correct reflect the api

- kubernetes/nodepool.go
- Fixed the k8s nodes return with correct message struct
> fix: change k8s nodes status return to me a single message field

- cmd/examples/kubernetes/main.go
- cmd/examples/kubernetes_small/main.go
- kubernetes/cluster.go
- Fix Cluster status message field to be a single item not an list.
> fix: adjust cluster message status field

- compute/instances.go
> feat: add omitzero in compute-instance idorname

- blockstorage/snapshots.go
- blockstorage/snapshots_test.go
- blockstorage/volumes.go
- cmd/examples/blockstorage/main.go
- Adjust the block storage field to reflect the correct pointers for optional fields
> fix: Update block storage structs with pointer types for optional fields

- blockstorage/volumes.go
- Fix Encryped field with correct pointer
> fix: Make Block Storage Encrypted field nullable with pointer type in Volume struct

- cmd/examples/dbaas/main.go
- dbaas/engines.go
- dbaas/engines_test.go
- dbaas/instance_types.go
- dbaas/instance_types_test.go
- dbaas/instances.go
- dbaas/instances_test.go
- Dbaas contracts adjust to use the correct pointers
- Remove some deprecated fields from instances
> fix: dbaas adjusted with correct pointers

- internal/http/client.go
- internal/http/client_test.go
- internal/retry/retry.go
- Fixed the scenario where retry requests would be without body
> fix: fixed retry logic that could make requests without body

- cmd/examples/network/main.go
- network/rules.go
- network/security_groups.go
> feat: update network

- availabilityzones/client.go
- client/client.go
- client/client_test.go
- sshkeys/client.go
- Fixed scenario where a config value could be changed inside a product instanciation.
> fix: client config handling to use value instead of pointer

- compute/instances.go
> fix: create vm instance with vpc id

- cmd/examples/network/main.go
- network/security_groups.go
- network/security_groups_test.go
> fix: create security group with queryparam

- cmd/examples/network/main.go
- network/client.go
- network/nat_gateways.go
- network/nat_gateways_test.go
```
=== NAT Gateway Examples ===
2025/04/29 13:52:40 INFO making request method=POST url=https://api.magalu.cloud/br-se1/network/v1/vpcs attempt=1
2025/04/29 13:52:42 INFO X-Request-ID received in response requestID=69375a4b-4b74-4a22-b992-4ff7dd6160df
2025/04/29 13:52:42 INFO X-Mgc-Trace-ID received in response mgcTraceID=08c07d46-ec50-4dca-bc48-9aa64288358d
Created VPC with ID: e34a4874-facf-4a6f-9d2c-4f100d2b96f8
2025/04/29 13:52:42 INFO making request method=POST url=https://api.magalu.cloud/br-se1/network/v1/nat_gateways attempt=1
2025/04/29 13:52:43 INFO X-Request-ID received in response requestID=c501880e-94d0-4d78-a774-d901d301df6e
2025/04/29 13:52:43 INFO X-Mgc-Trace-ID received in response mgcTraceID=76944bf3-cb44-4de0-9319-8154b9407201
2025/04/29 13:52:43 INFO making request …
```
> feat: network add natgateway

- README.md
- cmd/examples/dbaas/main.go
- dbaas/client.go
- dbaas/clusters.go
- dbaas/clusters_test.go
- dbaas/engines.go
- dbaas/engines_test.go
- dbaas/instance_types.go
- dbaas/instance_types_test.go
- dbaas/instances.go
- dbaas/instances_test.go
- dbaas/parameters.go
- dbaas/parameters_test.go
- dbaas/replicas.go
- dbaas/replicas_test.go
- Dbaas API's upgraded to v2 endpoints 
- Minor Dbaas current contracts changes
- New resources Clusters and Parameters
---
❗ BREAKING CHANGES ❗
API Version: The SDK now targets the DBaaS API v2. Ensure your client's base URL is configured correctly (e.g., https://api.magalu.cloud/<region>/database/v2). While the SDK handles the specific paths, this reflects a major underlying API version change.
Instances:
InstanceResizeRequest: Removed the FlavorID field. Use InstanceTypeID for resizing.
RestoreSnapshot Method (InstanceService):
Signature changed: Now requires instanceID in addition to snapshotID.
The underlying API path has changed.
Return type changed from *InstanceResponse to *InstanceDetail.
Replicas:
ReplicaCreateRequest: Removed the FlavorID field. Use InstanceTypeID if needed. …
> feat: dbaas v2 endpoints implemented, new parameters and clusters resources

- cmd/examples/dbaas/main.go
- dbaas/client.go
- dbaas/parameters.go
- dbaas/parameters_group.go
- dbaas/parameters_group_test.go
- dbaas/parameters_test.go
- Created the resource dbaas parameter, its a sub resource of parameters group
> feat: dbaas - implemented the parameters resource

- dbaas/instances.go
- dbaas/instances_test.go
- Dbaas snapshot resource fixed with correct pointers on optional fields
> fix: dbaas snapshot resource fixed with correct optional fields

- dbaas/instances.go
> fix: issue sonnar

- cmd/examples/compute/main.go
- compute/client.go
- compute/images.go
- compute/instances.go
- compute/instances_test.go
- compute/types.go
- compute/types_test.go
> feat: update compute module

- cmd/examples/dbaas/main.go
- dbaas/instance_types.go
- Added the new field for dbaas instance type - product compatible
> feat: new dbaas instances types field - compatible product

- kubernetes/cluster.go
- kubernetes/nodepool.go
- New K8s fields
- Cluster (Services and Cluster IPv4 CIDR)
- Nodepool (AZ and MaxPodPerNode)
> feat: added new fields for k8s nodepool (maxPodsPerNode and AZ) and cluster (ServicesIpv4CIDR and ClusterIPv4CIDR)

- compute/instances.go
> fix: compute

- network/ports.go
- Added new fields to network ports/nic for AZ
> feat: network ports with new az fields

- blockstorage/snapshots_test.go
- blockstorage/volumes_test.go
- dbaas/clusters_test.go
- dbaas/engines_test.go
- dbaas/instance_types_test.go
- dbaas/instances_test.go
- dbaas/replicas_test.go
- lbaas/network_acls_test.go
- lbaas/network_backend_targets_test.go
- lbaas/network_backend_test.go
- lbaas/network_certificates_test.go
- lbaas/network_healthchecks_test.go
- lbaas/network_listners_test.go
- lbaas/network_loadbalancers_test.go
- network/nat_gateways_test.go
- network/ports_test.go
- network/public_ips_test.go
- network/rules_test.go
- network/security_groups_test.go
- network/subnetpools_test.go
- network/subnets_test.go
- network/vpcs_test.go
Adds coverage for http status codes in error responses.
`make test`
> test: assert statuscode

- docs/main_generator.py
Fix heading in index file according to .rst files language
This wasn't tested
- [] I have added tests that prove my fix is effective or that my feature works
> docs: fix index file heading

- dbaas/clusters.go
Add a new field into the address model of the cluster response.
It has been tested along with the TF client provider.
> feat: improve dbaas cluster address model

- kubernetes/cluster.go
- New field attribute for K8s Cluster
- Create
- Get
- List
> feat: new k8s cluster field CNI (create and get/list)

- dbaas/instances.go
- dbaas/instances_test.go
Add the parameter `parameter-group-id`to DBaaS instances update
Unit tested.
> feat: add dbaas instances update parameter group
